apiVersion: v1
kind: Service
metadata:
  name: flask-loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-node-labels: nodegroup=flask-server
spec:
  type: LoadBalancer
  selector:
    app: flask-serve
  ports:
    - port: 80
      targetPort: 8080
      
      
